; vim: ft=dosini
; @changed 2026.10.06, 21:53
;
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
; Create/update the ccls configuration file:
; `pio init --ide vim`

[platformio]
extra_configs =
  platformio_override.in[i]

[core_settings]
; upload_port = COM3
; monitor_port = COM3
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs ; Connect LittleFS filesystem
monitor_filters = esp32_exception_decoder ; Decode exceptions in console
lib_deps =
  ; TFT Screen
  TFT_eSPI
  ; DS18B20 Temperature Sensor
  OneWire
  DallasTemperature
  ; Async Web Server
  ESP32Async/ESPAsyncWebServer
  ESP32Async/AsyncTCP
build_flags =
  ; Project core
  '-D PROJECT_NAME="pio-power-relay"' ; Project name string (quoted value)
  '-D PROJECT_INFO="v.0.0.1 / 2026.10.03 23:18:32 +0300"' ; Project info string (auto-upated, quoted value)
  ; Generic TFT settings
  -D TFT_ROTATION=3
  -D TFT_WIDTH=128
  -D TFT_HEIGHT=160
  ; TFT_eSPI library setting
  -D USER_SETUP_LOADED=1
  -D USER_SETUP_ID=2
  -D ST7735_DRIVER=1 ; Define additional parameters below for this display
  -D ST7735_GREENTAB3=1
  -D SPI_FREQUENCY=27000000
  -D SPI_READ_FREQUENCY=20000000
  -D SPI_TOUCH_FREQUENCY=2500000
  ; FONTS
  ; -D LOAD_GLCD=1   ; Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
  -D LOAD_FONT2=1  ; Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
  -D LOAD_FONT4=1  ; Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
  ; -D LOAD_FONT6=1  ; Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
  ; -D LOAD_FONT7=1  ; Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:.
  ; -D LOAD_FONT8=1  ; Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
  ; -D LOAD_GFXFF=1  ; FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts
  -D SMOOTH_FONT=1
  -D TOUCH_CS=21
  ; Other parameters
  '-D WIFI_CONFIGS_FILE="/wifi.txt"' ; Wifi configs file (with lines in format `SSID Password`). Overrides default values in `WIFI_CONFIGS`.
  ; '-D WIFI_CONFIGS={"SSID-1 Password", "SSID-2 Password"}' ; Default WiFi access points list (optional, quoted strings array)
  ; '-D WIFI_AP_SSID="espd"' ; Local wifi access point ssid
  ; '-D WIFI_AP_PWD="password"' ; Local wifi access point password
  -D TICK_DELAY=5000 ; Delay between main loop ticks (optional, undefined or 0 = single run)
  ; Default TFT PINOUT (Override in `platformio_override`)
  -D TFT_DC=2 ; Data Command control pin
  -D TFT_RST=14 ; Reset pin (could connect to RST pin)
  -D TFT_CS=17 ; Chip select control pin
  ; Power relay module setup
  -D RELAY_CH1=21 ; Power relay channel 1 pin
  -D RELAY_CH2=22 ; Power relay channel 2 pin
  ; SD Card Slot
  -D SD_CS=16 ; Sd Card Chip Select pin

[env:esp32dev]
extends = core_settings
